### ISSUE TITLE
elm-review --fix crashes on a certain NoUnsortedRecords operation

### ISSUE THREAD

**Issue by r-k-b** [SiriusStarr/elm-review-no-unsorted#2]
After installing `NoUnsortedRecords` I was able to `--fix` a few previous occurrences, but this one consistently fails:

<details><summary>"I ran into an unexpected error"</summary>

```shell
[rkb@nixos:~/projects/tularstmp]$ elm-review --fix
-- ELM-REVIEW ERROR ----------------------------------------- app/Main.elm:587:7

NoUnsortedRecords: Record fields are not sorted.

586|     in
587|     ( { agent
           ^
588|         | physics = newPhysics

Record fields were found out of order.  They should be sorted as specified in
the rule configuration.

I think I can fix this. Here is my proposal:

 588|         | physics = newPhysics
 589|         , topActionLastStartTimes = newTopActionLastStartTimes
 590|         , callingOut = newCall
 591|         , hunger = newHunger
 592|         , currentAction = topAction |> Maybe.map .name |> withDefault "none"
 593|         , currentOutcome = newOutcome
 594|         , holding = newHolding
 595|         , beggingForFood = beggingForFood
 596|         , hp = hitpointsAfterStarvation
 597|         , currentAction = topAction |> Maybe.map .name |> withDefault "none", currentOutcome = newOutcome, hunger = newHunger
 597|         , beggingForFood = beggingForFood, topActionLastStartTimes = newTopActionLastStartTimes, callingOut = newCall, holding = newHolding, hp = hitpointsAfterStarvation
 597|       }

✔ Do you wish to apply this fix? … yes

-- UNEXPECTED ERROR ------------------------------------------------------------

I ran into an unexpected error. Please open an issue at the following link:
  https://github.com/jfmengels/node-elm-review/issues/new

Please include this error message and as much detail as you can provide. If you
can, please provide a setup that makes it easy to reproduce the error. That will
make it much easier to fix the issue.

Below is the error that was encountered.
--------------------------------------------------------------------------------
Error: https://github.com/elm/core/blob/1.0.0/hints/5.md
    at _Debug_crash (/home/rkb/projects/tularstmp/elm-stuff/generated-code/jfmengels/elm-review/cli/2.5.5/review-applications/3835e632b06db71195022df297a481d6.js:460:8)
    at _Utils_eqHelp (/home/rkb/projects/tularstmp/elm-stuff/generated-code/jfmengels/elm-review/cli/2.5.5/review-applications/3835e632b06db71195022df297a481d6.js:554:30)
    at _Utils_eqHelp (/home/rkb/projects/tularstmp/elm-stuff/generated-code/jfmengels/elm-review/cli/2.5.5/review-applications/3835e632b06db71195022df297a481d6.js:587:8)
    at _Utils_eqHelp (/home/rkb/projects/tularstmp/elm-stuff/generated-code/jfmengels/elm-review/cli/2.5.5/review-applications/3835e632b06db71195022df297a481d6.js:587:8)
    at _Utils_eqHelp (/home/rkb/projects/tularstmp/elm-stuff/generated-code/jfmengels/elm-review/cli/2.5.5/review-applications/3835e632b06db71195022df297a481d6.js:587:8)
    at _Utils_eqHelp (/home/rkb/projects/tularstmp/elm-stuff/generated-code/jfmengels/elm-review/cli/2.5.5/review-applications/3835e632b06db71195022df297a481d6.js:587:8)
    at _Utils_eqHelp (/home/rkb/projects/tularstmp/elm-stuff/generated-code/jfmengels/elm-review/cli/2.5.5/review-applications/3835e632b06db71195022df297a481d6.js:587:8)
    at _Utils_eqHelp (/home/rkb/projects/tularstmp/elm-stuff/generated-code/jfmengels/elm-review/cli/2.5.5/review-applications/3835e632b06db71195022df297a481d6.js:587:8)
    at _Utils_eqHelp (/home/rkb/projects/tularstmp/elm-stuff/generated-code/jfmengels/elm-review/cli/2.5.5/review-applications/3835e632b06db71195022df297a481d6.js:587:8)
    at _Utils_eqHelp (/home/rkb/projects/tularstmp/elm-stuff/generated-code/jfmengels/elm-review/cli/2.5.5/review-applications/3835e632b06db71195022df297a481d6.js:587:8)
```

</details>

The issue may be related to the use of functions within the `ProjectContext`. <https://github.com/jfmengels/node-elm-review/issues/60>

# repro

```shell
$ git clone git@github.com:r-k-b/tulars.git

$ cd tulars

$ git checkout 424d21546444e1642de657f02874485814e5fae8

$ node --version
v14.17.6

$ npm i

$ elm-review --version
2.5.5

$ elm-review --fix
```

Hit `Y`, then crashes like the one shown above happen. It will crash the next few times too, but on different reported problems.

**Comment by SiriusStarr** [comment]
Fixed by b9a74c9.

Thanks for the report; please upgrade to 1.0.3 for the fix.
